# Makefile for FactorialSample
#
# Copyright (c) 2012, Eccam s.r.o.
# 
# All rights reserved.

# Configuration for windows32-mingw-intel
CC=g++
PLATFORM=windows32-mingw-intel
PLATFORM_CFLAGS=-m32
PLATFORM_LDFLAGS=-m32

include ../Makefile.mk

